@startuml
title /exit Sequence

autoactivate on
actor User
participant ":Ui" as Ui
participant ":CG2StocksTracker" as CG2StocksTracker
participant ":Parser" as Parser

User -> Ui : /exit
CG2StocksTracker -> Ui : readCommand()
Ui --> CG2StocksTracker : command text
CG2StocksTracker -> Parser : parse(...)
Parser --> CG2StocksTracker : EXIT
CG2StocksTracker -> Ui : showGoodbye()
CG2StocksTracker --> Ui : stop main loop
@enduml
