@startuml
title /help Sequence

actor User
participant ":Ui" as Ui
participant ":CG2StocksTracker" as CG2StocksTracker
participant ":Parser" as Parser
User -> Ui : /help
Ui -> CG2StocksTracker : command text
CG2StocksTracker -> Parser : parse(...)
Parser --> CG2StocksTracker : HELP
CG2StocksTracker -> Ui : showHelp()
@enduml
