@startuml
title /remove Sequence

actor User
participant ":Ui" as Ui
participant ":CG2StocksTracker" as CG2StocksTracker
participant ":Parser" as Parser
participant ":ParsedCommand" as ParsedCommand
participant ":PortfolioBook" as PortfolioBook
participant ":Portfolio" as Portfolio
participant ":Holding" as Holding
participant ":Storage" as Storage
User -> Ui : /remove --type ... --ticker ... [--qty] [--price]
Ui -> CG2StocksTracker : command text
CG2StocksTracker -> Parser : parse(...)
Parser --> CG2StocksTracker : REMOVE command
CG2StocksTracker -> ParsedCommand : totalFees()
CG2StocksTracker -> PortfolioBook : getActivePortfolio()
PortfolioBook --> CG2StocksTracker : Portfolio
CG2StocksTracker -> Portfolio : removeHolding(...)
Portfolio -> Holding : removeQuantity(...)
Portfolio --> CG2StocksTracker : RemoveResult
CG2StocksTracker -> Storage : save(...)
CG2StocksTracker -> Ui : show sold + realized P&L
@enduml
