@startuml
title /use Sequence

autoactivate on
actor User
participant ":Ui" as Ui
participant ":CG2StocksTracker" as CG2StocksTracker
participant ":Parser" as Parser
participant ":PortfolioBook" as PortfolioBook

User -> Ui : /use longterm
CG2StocksTracker -> Ui : readCommand()
Ui --> CG2StocksTracker : command text
CG2StocksTracker -> Parser : parse(...)
Parser --> CG2StocksTracker : USE(name)
CG2StocksTracker -> PortfolioBook : usePortfolio(name)
CG2StocksTracker -> Ui : show active portfolio
@enduml
