'@@author RishabhShenoy03
@startuml
title Value Command Class View

class Parser
class CG2StocksTracker
class PortfolioBook
class Portfolio
class Holding
class Ui

CG2StocksTracker --> PortfolioBook : getActivePortfolio()
CG2StocksTracker --> Ui : showPortfolioValue(portfolio)
Ui --> Portfolio
Portfolio --> Holding
@enduml
