@startuml
title /watch Sequence

actor User
participant ":Ui" as Ui
participant ":CG2StocksTracker" as CG2StocksTracker
participant ":Parser" as Parser
participant ":Watchlist" as Watchlist
participant ":PortfolioBook" as PortfolioBook
participant ":Storage" as Storage
User -> Ui : /watch <action> ...
Ui -> CG2StocksTracker : command text
CG2StocksTracker -> Parser : parse(...)
Parser --> CG2StocksTracker : WATCH(name=action,...)

alt action=list
  CG2StocksTracker -> Ui : showWatchlist(...)
else action=add/remove
  CG2StocksTracker -> Watchlist : addItem/removeItem
  CG2StocksTracker -> Storage : save(...)
  CG2StocksTracker -> Ui : show confirmation
else action=buy
  CG2StocksTracker -> Watchlist : buyItem(...,portfolioBook)
  Watchlist -> PortfolioBook : getPortfolio(...)
  CG2StocksTracker -> Storage : save(...)
  CG2StocksTracker -> Ui : show bought output
end
@enduml
